[package]
name = "recall-cli"
description = "The recall command-line interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[lints]
workspace = true

[[bin]]
name = "recall"
path = "src/main.rs"

[dependencies]
recall-core = { path = "../recall-core" }
recall-adapters = { path = "../recall-adapters" }
recall-store = { path = "../recall-store" }
recall-index = { path = "../recall-index" }
